Feat/be registration
povkas/Eshop pull request #18
Opened 2019-03-18 19:51 UTC by JustMoze

Pofka ar dabar gerai? 🗡 😄

2019-03-18 20:04 UTC, povkas commented
Rodo, kad yra konfliktų

2019-03-18 20:11 UTC, povkas commented
Reiktų postmano requesto

2019-03-18 20:18 UTC, povkas requested changes
Pataisyk klaidas

2019-03-18 20:18 UTC, povkas commented on back-end/Eshop/Startup.cs
> +            services.SetUpDatabase(Configuration);
Kodas kartojasi
 ir nepalik užkomentuoto kodo

2019-03-18 20:18 UTC, povkas commented on back-end/Eshop/Services/RegistrationService.cs
> +        public async Task<bool> CheckUserExistence(User newbie)
newbie turbūt nelabai geras vardas, geriau koks newUser ar pan.

2019-03-18 20:18 UTC, povkas commented on back-end/Eshop/Data/Repositories/UsersRepository.cs
> +        public bool CreateUser(User user)
Vietoj naujo metodo, galėtum panaudoti jau esamą, Create, nereikės data ir context'o iškvietinėti čia

2019-03-18 20:18 UTC, povkas commented on back-end/Eshop/Services/RegistrationService.cs
> +        private readonly IRepository<User> repo;
_repository, parsisiųsk resharper'į, rodys pasiūlymą pakeisti vardą

2019-03-18 20:18 UTC, povkas commented on back-end/Eshop/Data/SeedData.cs
> -            var products = new List<Product>
nepalik užkomentuoto

2019-03-21 15:07 UTC, povkas approved these changes

2019-03-21 17:43 UTC, DeiVarnagis approved these changes

2019-03-21 17:50 UTC, merged