Feat/F_Login_Form
povkas/Eshop pull request #19
Opened 2019-03-19 17:35 UTC by iMckify

completed the Login FE task listed in the backlog, however Login Modal does only open while clicked on the Person icon precisely and not on its background, also POST request is not completed yet

2019-04-16 17:24 UTC, povkas requested changes

2019-04-16 17:24 UTC, povkas commented on back-end/Eshop/Data/SeedData.cs
> +//                return;
Palik neužkomentuota

2019-04-16 17:24 UTC, povkas commented on front-end/src/components/login/Form.js
> +      <div>
nereikalingas div'as

2019-04-16 17:24 UTC, povkas commented on front-end/src/components/login/LoginForm.js
> +            {/* eslint-disable-next-line react/no-unescaped-entities */}
Pašalink eslint'o komentarus

2019-04-16 17:24 UTC, povkas commented on front-end/src/components/login/Form.js
> +        email.indexOf('@') > email.lastIndexOf('.') ||
Naudok regex'ą

2019-04-16 17:24 UTC, povkas commented on front-end/src/components/login/UserOptions.js
> +      anchorEl: null
pervadink kintamąjį, nes neaišku, kokia jo paskirtis

2019-04-16 17:24 UTC, povkas commented on front-end/src/components/snackbars/SnackbarContainer.js
> +class SnackbarContainer extends React.Component {
Jei component'as stateless, tai klasę perrašyk į funkciją

2019-04-16 17:24 UTC, povkas commented on front-end/src/containers/MainBody.js
> +      variant: ''
pakeist pavadinimą, kad būtų aiškiau snackbarVariant ar kažkaip

2019-04-16 17:24 UTC, povkas commented on front-end/src/components/snackbars/SnackbarContainer.js
> +const stylesWrap = theme => ({
Perkelk stilius

2019-04-16 17:24 UTC, povkas commented on front-end/src/components/snackbars/SnackbarContainer.js
> +const variantMessage = {
iškelk prie konstantų

2019-04-16 17:24 UTC, povkas commented on front-end/src/components/snackbars/SnackbarContainer.js
> +function MySnackbarContent(props) {
Iškelk į naują failą

2019-04-16 17:24 UTC, povkas commented on front-end/src/components/login/Form.js
> +      errors.emailErrorText = 'Email is required';
errorų žinutes iškelk prie konstantų

2019-04-18 16:47 UTC, iMckify commented on front-end/src/containers/MainBody.js
> +      variant: ''
jau buvo pakeista ;)

2019-04-18 16:47 UTC, iMckify commented on front-end/src/components/snackbars/SnackbarContainer.js
> +const stylesWrap = theme => ({
jie jau yra perkelti ;P

2019-04-22 16:35 UTC, povkas approved these changes

2019-04-22 20:07 UTC, gGvidas approved these changes

2019-04-22 21:52 UTC, merged