Feat/be login
povkas/Eshop pull request #20
Opened 2019-03-21 18:22 UTC by DeiVarnagis

2019-03-21 20:27 UTC, povkas requested changes

2019-03-21 20:27 UTC, povkas commented on back-end/Eshop/libman.json
> +}
Mums reikia šio failo?

2019-03-21 20:27 UTC, povkas commented on back-end/Eshop/Properties/launchSettings.json
> +      "launchBrowser": true,
Užstatyk į false, nebūtina kiekvieną kartą turėt atidarytą browserį

2019-03-21 20:27 UTC, povkas commented on back-end/Eshop/Controllers/LoginController.cs
> +    {
Mentorius sakė pakeist į UserController

2019-03-21 20:27 UTC, povkas commented on back-end/Eshop/Data/SeedData.cs
nepalik užkomentuoto kodo

2019-03-21 20:27 UTC, povkas commented on back-end/Eshop/Migrations/20190305110502_InitialCreate.cs
>                  },
kodėl keičiamos migracijos?

2019-03-21 20:27 UTC, povkas commented on back-end/Eshop/Migrations/ContextModelSnapshot.cs
Kodėl čia keičiama?

2019-03-21 20:27 UTC, povkas commented on back-end/Eshop/Models/User.cs
>          [Required(AllowEmptyStrings = false, ErrorMessage = "Country required ")]
kam čia /n?

2019-03-21 20:27 UTC, povkas commented on back-end/Eshop/Models/User.cs
>          [Required(AllowEmptyStrings = false, ErrorMessage = " Name required ")]
kam čia /n

2019-03-21 20:27 UTC, povkas commented on back-end/Eshop/Startup.cs
>              services.SetUpAutoMapper();
?

2019-03-23 15:47 UTC, povkas approved these changes

2019-03-23 15:48 UTC, gGvidas approved these changes

2019-03-23 15:49 UTC, merged