Feat/FE single product's modal
povkas/Eshop pull request #25
Opened 2019-04-01 13:31 UTC by iMckify

added triple layer props, simplified modal opener, added color in ProductModal state in order to substarct it from ColorSelect

2019-04-01 16:00 UTC, povkas requested changes

2019-04-01 16:00 UTC, povkas commented on back-end/Eshop/Migrations/ContextModelSnapshot.cs
> -
palik tarpą

2019-04-01 16:00 UTC, povkas commented on back-end/E-shop.postman_collection.json
> +  "info": {
kas čia keičiama?

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/product/ColorSelect.js
> +      open: false
nelabai aiškus kintamojo pavadinimas

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/product/ProductModal.js
> +  // added image styles
nereikalingas komentaras

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/product/ProductModal.js
> +      // eslint-disable-next-line react/no-unused-state
nepalik eslint'o komentarų

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/product/ProductModal.js
> +    // eslint-disable-next-line react/no-unused-state
tas pats ir čia

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/product/ProductModal.js
> +                  <Star className={classes.star} />
Siūlau pašalinti žvaigždutes, nes bent kol kas jos neturi jokios fukncijos

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/product/ProductModal.js
> +  classes: PropTypes.shape().isRequired
Nėra patikrinami visi props'ai

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/productTable/ProductItem.js
> +/* upper two are required for the eslint in <b onClick> */
jeigu nepavyksta pašalinti bėdos, tai pakeisk eslint'o tasyklę, bet nepalik tokių komentarų

2019-04-01 16:00 UTC, povkas commented on front-end/src/containers/MainBody.js
> +    // eslint-disable-next-line no-unused-vars
ištrink

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/login/LoginForm.js
> +  classes: PropTypes.shape().isRequired
ne visi props'ai

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/login/LoginForm.js
> +            {/* eslint-disable-next-line react/no-unescaped-entities */}
Pasistenk nepalikti eslint'o komentarų

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/product/ColorSelect.js
> +const styles = theme => ({
eksportuok stilių į naują failą styles.js

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/product/ProductModal.js
> +const styles = theme => ({
eksportuok stilių

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/product/ProductModal.js
> +function getModalStyle() {
Numesk funkciją į utils arba prie styles.js

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/product/ProductModal.js
> +      <div>
ar reikia modalą dar dėti į vidų?

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/productTable/ProductTable.js
>  import React from 'react';
![image](https://user-images.githubusercontent.com/26685992/55341845-11231580-54b0-11e9-858a-c6feb3a3e486.png)

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/productTable/ProductTable.js
>  import React from 'react';
reiktų pašalint

2019-04-01 16:00 UTC, povkas commented on front-end/src/components/productTable/ProductTable.js
>  import React from 'react';
taip pat turi idėti galimybę pasirinkti produktų kiekį

2019-04-01 16:12 UTC, iMckify commented on front-end/src/components/product/ProductModal.js
> +  // added image styles
true, buvau istrynes, bet uzsiliko

2019-04-01 16:12 UTC, iMckify commented on front-end/src/components/product/ProductModal.js
> +      // eslint-disable-next-line react/no-unused-state
be ju negaliu pushint

2019-04-03 08:49 UTC, JustMoze commented on front-end/src/components/product/ProductModal.js
> +            <ColorSelect getColor={this.getColor} />
Manau, kad color select siuo metu nereiktu implementuot, nes sis option tinka tik kai kuriu kategoriju prekems, o dabar neskirstysim sito.

2019-04-03 08:49 UTC, JustMoze commented on front-end/src/components/product/ProductModal.js
> +            <ColorSelect getColor={this.getColor} />
Gvidas cia btw lol

2019-04-03 08:49 UTC, JustMoze commented on front-end/src/components/product/QuantitySelect.js
> +  };
Man rodos, cia nepatikrina, ar toks quantity produktu isvis yra, ar ne?

2019-04-03 08:57 UTC, iMckify commented on front-end/src/components/product/ProductModal.js
> +            <ColorSelect getColor={this.getColor} />
backloge aprasyta, kad darysim, kita karta reiketu backlog tikrint pries pradedant dirbt -_-

2019-04-03 09:00 UTC, iMckify commented on front-end/src/components/product/QuantitySelect.js
> +  };
padariau per daug nesigilindamas, nes tuo metu buvo svarbiau, kad veiktu, o del maximum quantity  nesu girdejes, reikia susiderinti visiem

2019-04-04 10:41 UTC, gGvidas approved these changes

2019-04-06 06:20 UTC, povkas approved these changes

2019-04-06 06:41 UTC, merged