Feat/fe filter
povkas/Eshop pull request #27
Opened 2019-04-05 20:41 UTC by gGvidas

2019-04-06 15:49 UTC, povkas requested changes

2019-04-06 15:49 UTC, povkas commented on front-end/src/components/productTable/ProductTable.js
> +      productsOnDisplay: [],
Pakeisk į filtered products, bus aiškiau

2019-04-06 15:49 UTC, povkas commented on front-end/src/containers/MainBody.js
> +      productsOnDisplay: [],
Geriau pavadinti filtered products

2019-04-06 15:49 UTC, povkas commented on front-end/src/containers/MainBody.js
> +      productsOnDisplay: [],
Ir jeigu tuščias, tai parašyk, kad nėra produktų pagal pasirinktus filtrus

2019-04-06 15:52 UTC, povkas commented on front-end/src/containers/Styles.js
> +const color = grey[100];
liko stilius MainBody faile

2019-04-06 16:31 UTC, povkas approved these changes

2019-04-08 10:41 UTC, DeiVarnagis approved these changes

2019-04-08 13:46 UTC, merged