Feat FE drop down menu
povkas/Eshop pull request #29
Opened 2019-04-13 18:08 UTC by DeiVarnagis

2019-04-14 18:08 UTC, povkas requested changes

2019-04-14 18:08 UTC, povkas commented on front-end/src/components/categoriesList/CategoriesList.js
> +
Nereik tarpo

2019-04-14 18:08 UTC, povkas commented on front-end/src/utils/constants/categoriesApi.js
> +const categories = 'http://localhost:5000/api/product-categories';
įmesk konstantą prie kitų api konstantų, jei neklystų api.js faile

2019-04-14 18:08 UTC, povkas commented on front-end/src/components/categoriesList/CategoriesList.js
> +// eslint-disable-next-line import/no-duplicates
pašalink eslint komentarus

2019-04-14 18:10 UTC, povkas requested changes

2019-04-14 18:10 UTC, povkas commented on front-end/src/components/categoriesList/CategoriesList.js
> +                  selectCategory('All Products');
Padaryk konstanta, nes dabar per kelis failus tas pats stringas

2019-04-14 18:11 UTC, povkas commented on front-end/src/components/categoriesList/CategoriesList.js
> +                  selectCategory('All Products');
All vietoje All Products atrodytų geriau?

2019-04-15 17:30 UTC, povkas approved these changes

2019-04-15 17:47 UTC, gGvidas approved these changes

2019-04-15 17:50 UTC, merged