Feat fe registration
povkas/Eshop pull request #30
Opened 2019-04-17 11:08 UTC by DeiVarnagis

2019-04-26 16:18 UTC, povkas requested changes

2019-04-26 16:18 UTC, povkas commented on back-end/Eshop/Startup.cs
> +        // This method gets called by the runtime. Use this method to add services to the container.
pašalink komentarą

2019-04-26 16:18 UTC, povkas commented on back-end/Eshop/Startup.cs
> +        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
pašalink komentarą

2019-04-26 16:18 UTC, povkas commented on back-end/Eshop/Startup.cs
> +                ctx.Response.StatusCode = 404;
palik statusą, kaip buvo

2019-04-26 16:18 UTC, povkas commented on back-end/Eshop/Startup.cs
> +                .UseCors(builder =>
nereikalingi tarpai

2019-04-26 16:18 UTC, povkas commented on front-end/src/components/registration/Form.js
> +      isConfirmPassword: false
Perdaryk validaciją taip, kad nereikėtų isError boolean'ų, užtektų tik patikrint ar error text'as tuščias ar ne. Tuo pačiu reikės pakeisti errorText'us į tuščius stringus

2019-04-26 16:18 UTC, povkas commented on front-end/src/components/registration/Form.js
> +    e.preventDefault(); // preventing browser to reload
nebūtinas komentaras

2019-04-26 16:18 UTC, povkas commented on front-end/src/components/registration/Form.js
> +    const url = `http://localhost:5000/api/user`;
perkelk prie konstantų

2019-04-26 16:18 UTC, povkas commented on front-end/src/components/registration/Form.js
> +        if (error.response) {
pridėk default error response, jei neatpažintas error'as

2019-04-26 16:18 UTC, povkas commented on front-end/src/components/registration/RegistrationForm.js
> +    const { classes, openSnackbar, closeRegistration, openRegistrationModal } = this.props;
pervalink iš openRegistrationModal į isOpenRegistrationModal, kad būtų aišku, jog tai boolean'as

2019-04-26 16:18 UTC, povkas commented on front-end/src/components/registration/Styles.js
> +export const styles1 = {
styles1 blogas pavadinimas

2019-04-26 16:18 UTC, povkas commented on front-end/src/components/snackbar/Styles.js
> +  registrationSuccess: {
pernaudok "success" stilių

2019-04-26 16:18 UTC, povkas commented on front-end/src/components/snackbar/Styles.js
> +  registrationFailed: {
pernaudok "error" stilių

2019-04-26 16:18 UTC, povkas commented on front-end/package-lock.json
>          }
Kodėl pas tave šis failas taip skiriasi nuo mūsų? Pabandyk padaryt npm i ir pažiūrėk, kaip pasikeis dependencies

2019-04-26 16:18 UTC, povkas commented on back-end/Eshop/Startup.cs
> +
Čia taip pat be reikalo praleista eilutė

2019-04-26 20:58 UTC, povkas requested changes

2019-04-26 20:58 UTC, povkas commented on front-end/src/components/registration/Form.js
> +      if (email.indexOf('@') === -1 || email.indexOf('.') === -1 || email.length > 128) {
Išeksportuok kiekvieną ifų grupę į utils/validation/registration

2019-04-26 20:58 UTC, povkas commented on front-end/src/components/registration/Form.js
> +        } else if (error.request) {
Čia nereikia else if, užtenka if, o šiaip siūlau pernaudoti setError metodą apibrėžtą MainBody componente

2019-04-26 20:58 UTC, povkas commented on front-end/src/components/registration/Form.js
> +        } else if (error.request) {
Pažiūrėk, kaip padaryta actions/authentication faile

2019-04-26 20:58 UTC, povkas commented on front-end/src/components/registration/Form.js
> +            onBlur={this.validate}
Kai pasirašysi atskirus metodus skirtingų text fieldų validacijai, galėsi kvietsi kiekvieną metodą atskirtai, o ne validuoti viską kartu

2019-04-26 20:58 UTC, povkas commented on front-end/src/utils/constants/snackbarMessages.js
> +  registrationFailed: 'Email has already been taken!',
error'o žinutė turi būti gaunama iš backend'o, pernaudok setError metodą ir gausi tinkamą žinutę, šią galėsi ištrint

2019-04-26 20:59 UTC, povkas commented on back-end/Eshop/Startup.cs
> +                 builder.WithOrigins("http://localhost:3000")
palik formatavimą, koks buvo

2019-04-26 21:00 UTC, povkas commented on back-end/Eshop/Controllers/UsersController.cs
> -
palik tuščią eilutę

2019-04-28 12:49 UTC, gGvidas commented on front-end/package.json
> +    "react-native-expo-viewport-units": "0.0.8",
Kam šitas reikalingas?

2019-04-29 08:06 UTC, povkas approved these changes

2019-04-29 11:00 UTC, gGvidas approved these changes

2019-04-29 12:55 UTC, merged