Feat fe validation fixes
povkas/Eshop pull request #43
Opened 2019-05-24 16:24 UTC by DeiVarnagis

validation/design

2019-05-26 13:25 UTC, iMckify approved these changes

2019-05-27 18:49 UTC, gGvidas commented on front-end/src/components/login/Styles.js
> +    top: `${9}%`,
Palik 64px

2019-05-27 19:06 UTC, povkas requested changes

2019-05-27 19:06 UTC, povkas commented on front-end/src/utils/constants/registrationErrors.js
> +  nameErrorLong: 'Name must contain less then 30 symbols',
less than*

2019-05-27 19:57 UTC, gGvidas approved these changes

2019-05-27 20:18 UTC, povkas approved these changes

2019-05-27 20:19 UTC, merged